#!/bin/bash
# /etc/init.d/actions_dash

### BEGIN INIT INFO
# Provides:          actions_dash
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: actions_dash
# Description:       Python script pour exécuter des commandes à l'appui sur les boutons
### END INIT INFO


case "$1" in 
    start)
        echo "Starting actions_dash"
        echo "  python /home/pi/domoticz/scripts/python/AmazonDash/actions_dash.py &"
        python /home/pi/domoticz/scripts/python/actions_dash.py &
        ;;
    stop)
        echo "Stopping actions_dash"
        echo '  pkill -f "python /home/pi/domoticz/scripts/python/AmazonDash/actions_dash.py"'
        pkill -f "python /home/pi/domoticz/scripts/python/AmazonDash/actions_dash.py"
        ;;
	reload|restart)
		$0 stop
		sleep 1
		$0 start
		;;
    *)
        echo "Usage: $0 {start|stop|reload|restart}"
        exit 1
        ;;
esac

exit 0