#!/bin/bash
# /etc/init.d/amazondash

### BEGIN INIT INFO
# Provides:          amazondash
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: amazondash
# Description:       Python script pour exécuter des commandes à l'appui sur les boutons AmazonDash
### END INIT INFO

PATH=/sbin:/usr/sbin:/bin:/usr/bin
NAME=amazondash
PYTHON_SCRIPT="python /home/pi/domoticz/scripts/python/amazondash/amazondash.py"
PIDFILE=/var/run/$NAME.pid

case "$1" in 

    start)
        if [ -a "$PIDFILE" ]; then  # Exit if the pid file already exists
            echo "$NAME is already running" 
            exit 0
        fi
        echo "Starting $NAME ..."
        echo "  $PYTHON_SCRIPT &"
        $PYTHON_SCRIPT &
        # Get its PID and store it
        echo $! > $PIDFILE 
        ;;

    stop)
        echo "Stopping $NAME ..."
        echo '  pkill -f "'$PYTHON_SCRIPT'"'
        pkill -f "$PYTHON_SCRIPT"
        rm -rf $PIDFILE 
        ;;

    reload|restart)
        $0 stop
        sleep 3
        $0 start
        ;;

    status)
        ps aux | head -1; ps aux | grep "$PYTHON_SCRIPT" | grep -v "grep $PYTHON_SCRIPT"
        ;;

    *)
        echo "Usage: $0 {start|stop|reload|restart|status}"
        exit 1
        ;;
esac

exit 0
